title = "TOML Example"

[ServerConfig]
Port = 32452
MaxClientCount = 1000
ExtraClientCount = 64
BackLogCount = 128
MaxClientRecvBufferSize = 8192
MaxClientSendBufferSize = 8192
MaxRoomUserCount = 4
MaxRoomCountByLobby = 100
RedisAddress = "127.0.0.1"
RedisPortNum = 6379
maxIOWorkerThreadCount = 4